### ISSUE TITLE
Nodered server stops

### ISSUE THREAD

**Issue by goofy2k** [drmibell/node-red-contrib-random-event-generator#1] opened 2020-07-03 09:36 UTC
I have tested the node under nodered V 1.1.0, running under Docker.   When I edit the average delay time, my nodered server stops and I have to restarts the docker container.

I decided to remove the node from my palette. At first I removed the node in my test flow. When I then want to remove the node from my flow the server replies that it can not be removed, because it is still active.

I like the functionality !

**Comment by drmibell** [comment] 2020-07-04 21:18
You may have found two distinct issues. One is the crash of Node-RED, and the other is the inability to delete the node from the palette. 

I have reproduced the second issue and started looking into it. It might be helpful to know whether you have run into it with earlier versions of NR or other contributed nodes.

I have seen only one fatal error from the node and have not been able to reproduce it. It would help greatly if you could list a series of steps that reliably produces the error and send me any error messages you get. (I don't use Docker, so I can't tell you where to look for the error log.) Also please explain why you need to restart the container.

Thanks for bringing this to my attention.

**Comment by goofy2k** [comment] 2020-07-04 21:31
Hi Michael,

I a pretty new in docker so I find it hard to get the logs. My main purpose
was to bring the (potential) problems under your attention.

I have some further remarks for you.

1. Nodered 1.1.0 is pretty fresh and so is the combination with docker.
2. Later I noticed that unistallation of other contrib nodes was also not
possible
3. More precisely the behaviour that I observed was  that the docker
container stopped running. It happened when I was changing the average time
for the exponential distribution.

Fred



Op za 4 jul. 2020 23:19 schreef Michael I Bell <notifications@github.com>:

**Comment by goofy2k** [comment] 2020-07-04 22:17
Hi Michael,

I re-installed your node and had a look.

I can normally un-install it just like other custom modules. I just have to
make sure that it is not in use in a flow ;-).

The shut down of my docker container still happens. It occurs when I edit
the time constant and then deploy the changed flow.

I also found the nodered log in docker, but it does not contain a hint. It
apparently shuts down very abruptly.

Cheers
Fred

Op za 4 jul. 2020 23:31 schreef goofy2k <goofy2k@gmail.com>:

**Comment by drmibell** [comment] 2020-07-04 23:39
Thanks for the new information. I also get the correct behavior now in the Manage Palette dialog. It's a puzzle, but unless it misbehaves again there isn't anything I can do. 

I managed to get another NR shutdown, with the same error message as the first time. I can see where the error occurs, but I don't know why it happens and cannot trigger it reliably. I have a few ideas and will let you know if make any progress.

**Comment by goofy2k** [comment] 2020-07-05 08:39
Thanks! I certainly like the functionality of your node.

Fred

Op zo 5 jul. 2020 01:39 schreef Michael I Bell <notifications@github.com>:

**Comment by drmibell** [comment] 2020-07-06 17:49
I have pushed a new version (0.0.4) to GitHub that MIGHT solve this issue. I am not certain, because I can't produce the error reliably and so am working from a guess about the cause. Please let me know if the new version seems to help.

**Comment by wnasich** [comment] 2020-11-01 14:24
I started with v 0.0.3 and I had this issue also with v 0.0.4, I submitted a pull request that could solve it

**Comment by drmibell** [comment] 2020-11-01 18:30
Thanks very much for the PR. I will merge it into the the master shortly. It was clearly a JavaScript beginner's mistake and a particularly embarrassing one -- I always complain that JS does not give enough control over the scope of variables, and here I tripped over one of the few cases where it does.

**Comment by drmibell** [comment] 2021-04-15 19:47
Fixed in version 0.1.0

**Closed as completed by drmibell** 2021-04-15 19:47 UTC
